# Services package
"""Services for the Autism Science Tutor application."""

from src.services.content_ingestion import (
    ContentIngestionService,
    ProcessingResult,
    TextExtractor,
    TextChunker,
)
from src.services.rag_engine import (
    RAGEngine,
    RAGResponse,
    QueryContext,
    Chunk,
    Source,
)
from src.services.profile_service import (
    ProfileService,
    Interaction,
)
from src.services.chat_orchestrator import (
    ChatOrchestrator,
    ChatResponse,
    UserInput,
    ComprehensionOption,
    OutputModeOption,
    ExplanationPart,
    VisualAid,
    SessionState,
)
from src.services.multimodal_input import (
    MultimodalInputHandler,
    ProcessedInput,
    Intent,
    Entity,
    STTService,
    VisionService,
    MockSTTService,
    MockVisionService,
)
from src.services.multimodal_output import (
    MultimodalOutputRenderer,
    RenderedText,
    TextStyle,
    VoiceConfig,
    VisualType,
    VisualData,
    VisualAid as OutputVisualAid,
    ButtonGroup,
    TTSService,
    ImageService,
    MockTTSService,
    MockImageService,
)
from src.services.progress_tracker import (
    ProgressTracker,
    AchievementType,
    ACHIEVEMENT_DEFINITIONS,
    REVIEW_THRESHOLD,
    MASTERY_THRESHOLD,
)
from src.services.guardian_service import (
    GuardianService,
    IndependenceMetrics,
    WeeklyMetric,
    AlertType,
    GuardianAlert,
)
from src.services.calm_mode import (
    CalmModeService,
    BreakSession,
    BreathingSession,
    BreathingPattern,
    BreathingPhase,
    AudioStream,
    CalmingContent,
    DEFAULT_CALMING_CONTENT,
    CALMING_MUSIC_TRACKS,
)
from src.services.avatar_service import (
    AvatarStateService,
    AvatarState,
    AvatarType,
    AvatarConfig,
    AvatarStateChange,
    AvatarStatus,
    DEFAULT_TUTOR_AVATAR,
    DEFAULT_STUDENT_AVATAR,
)
from src.services.interface_preferences import (
    InterfacePreferencesService,
    InterfaceCustomization,
    InterfacePreferencesUpdate,
    InterfaceState,
    SpacingSettings,
)

# These require heavy dependencies and are imported lazily
# EmbeddingService and ChromaDBClient are available via:
# from src.services.content_ingestion import EmbeddingService, ChromaDBClient

__all__ = [
    "ContentIngestionService",
    "ProcessingResult",
    "TextExtractor",
    "TextChunker",
    "RAGEngine",
    "RAGResponse",
    "QueryContext",
    "Chunk",
    "Source",
    "ProfileService",
    "Interaction",
    "ChatOrchestrator",
    "ChatResponse",
    "UserInput",
    "ComprehensionOption",
    "OutputModeOption",
    "ExplanationPart",
    "VisualAid",
    "SessionState",
    "MultimodalInputHandler",
    "ProcessedInput",
    "Intent",
    "Entity",
    "STTService",
    "VisionService",
    "MockSTTService",
    "MockVisionService",
    "MultimodalOutputRenderer",
    "RenderedText",
    "TextStyle",
    "VoiceConfig",
    "VisualType",
    "VisualData",
    "OutputVisualAid",
    "ButtonGroup",
    "TTSService",
    "ImageService",
    "MockTTSService",
    "MockImageService",
    "ProgressTracker",
    "AchievementType",
    "ACHIEVEMENT_DEFINITIONS",
    "REVIEW_THRESHOLD",
    "MASTERY_THRESHOLD",
    "GuardianService",
    "IndependenceMetrics",
    "WeeklyMetric",
    "AlertType",
    "GuardianAlert",
    "CalmModeService",
    "BreakSession",
    "BreathingSession",
    "BreathingPattern",
    "BreathingPhase",
    "AudioStream",
    "CalmingContent",
    "DEFAULT_CALMING_CONTENT",
    "CALMING_MUSIC_TRACKS",
    "AvatarStateService",
    "AvatarState",
    "AvatarType",
    "AvatarConfig",
    "AvatarStateChange",
    "AvatarStatus",
    "DEFAULT_TUTOR_AVATAR",
    "DEFAULT_STUDENT_AVATAR",
    "InterfacePreferencesService",
    "InterfaceCustomization",
    "InterfacePreferencesUpdate",
    "InterfaceState",
    "SpacingSettings",
]
