"""Property-based tests for MultimodalOutputRenderer.

Feature: autism-science-tutor, Property 9: Text Output Presence
Validates: Requirements 4.1

This test validates that for any ChatResponse generated by the system,
it SHALL contain a non-empty message text field.
"""

import pytest
from hypothesis import given, settings, strategies as st, assume, HealthCheck

from src.services.multimodal_output import (
    MultimodalOutputRenderer,
    RenderedText,
    TextStyle,
    VoiceConfig,
    VisualType,
    VisualData,
    VisualAid,
    ButtonGroup,
    ComprehensionOption,
    MockTTSService,
    MockImageService,
)


# Strategies for generating valid test data

# Strategy for generating text content
text_content_strategy = st.text(
    alphabet=st.characters(whitelist_categories=("L", "N", "Zs", "Po")),
    min_size=1,
    max_size=1000,
).filter(lambda x: x.strip())

# Strategy for generating non-empty text
non_empty_text_strategy = st.text(
    alphabet=st.characters(whitelist_categories=("L", "N", "Zs")),
    min_size=5,
    max_size=500,
).filter(lambda x: len(x.strip()) >= 5)

# Strategy for generating explanation-like text
explanation_text_strategy = st.sampled_from([
    "Photosynthesis is the process by which plants convert sunlight into energy.",
    "Water exists in three states: solid, liquid, and gas.",
    "Gravity is a force that attracts objects toward each other.",
    "The solar system consists of the Sun and all objects that orbit it.",
    "Cells are the basic building blocks of all living organisms.",
    "Energy cannot be created or destroyed, only transformed.",
    "The Earth rotates on its axis once every 24 hours.",
    "Atoms are made up of protons, neutrons, and electrons.",
    "Sound travels in waves through air, water, and solids.",
    "The human body has 206 bones in the adult skeleton.",
])

# Strategy for font sizes
font_size_strategy = st.sampled_from(["small", "medium", "large"])

# Strategy for visual types
visual_type_strategy = st.sampled_from(list(VisualType))

# Strategy for topics
topic_strategy = st.sampled_from([
    "photosynthesis",
    "gravity",
    "water cycle",
    "solar system",
    "cells",
    "atoms",
    "electricity",
    "magnetism",
    "digestion",
    "respiration",
])


class TestTextOutputPresence:
    """
    Property 9: Text Output Presence
    
    For any ChatResponse generated by the system, it SHALL contain 
    a non-empty message text field.
    
    Validates: Requirements 4.1
    """

    @given(content=non_empty_text_strategy)
    @settings(max_examples=100, deadline=None, suppress_health_check=[HealthCheck.too_slow])
    def test_render_text_returns_non_empty_content(
        self,
        content: str,
    ):
        """
        Feature: autism-science-tutor, Property 9: Text Output Presence
        Validates: Requirements 4.1
        
        For any non-empty text content, render_text SHALL return a 
        RenderedText with non-empty content field.
        """
        assume(len(content.strip()) >= 5)
        
        renderer = MultimodalOutputRenderer()
        result = renderer.render_text(content)
        
        # Property: SHALL return a RenderedText
        assert isinstance(result, RenderedText), (
            "render_text SHALL return a RenderedText"
        )
        
        # Property: content SHALL be non-empty for non-empty input
        assert result.content is not None, (
            "RenderedText.content SHALL not be None"
        )
        assert isinstance(result.content, str), (
            "RenderedText.content SHALL be a string"
        )
        assert len(result.content) > 0, (
            "RenderedText.content SHALL be non-empty for non-empty input"
        )

    @given(content=explanation_text_strategy)
    @settings(max_examples=100, deadline=None, suppress_health_check=[HealthCheck.too_slow])
    def test_render_text_preserves_explanation_content(
        self,
        content: str,
    ):
        """
        Feature: autism-science-tutor, Property 9: Text Output Presence
        Validates: Requirements 4.1
        
        For any explanation text, render_text SHALL preserve the 
        essential content in the output.
        """
        renderer = MultimodalOutputRenderer()
        result = renderer.render_text(content)
        
        # Property: content SHALL be preserved
        assert result.content == content, (
            "render_text SHALL preserve the input content"
        )
        
        # Property: word_count SHALL be positive
        assert result.word_count > 0, (
            "word_count SHALL be positive for non-empty content"
        )
        
        # Property: reading_time_seconds SHALL be positive
        assert result.reading_time_seconds > 0, (
            "reading_time_seconds SHALL be positive for non-empty content"
        )

    @given(
        content=non_empty_text_strategy,
        font_size=font_size_strategy,
        bold=st.booleans(),
        italic=st.booleans(),
    )
    @settings(max_examples=100, deadline=None, suppress_health_check=[HealthCheck.too_slow])
    def test_render_text_with_style_returns_non_empty_content(
        self,
        content: str,
        font_size: str,
        bold: bool,
        italic: bool,
    ):
        """
        Feature: autism-science-tutor, Property 9: Text Output Presence
        Validates: Requirements 4.1
        
        For any text content with any style configuration, render_text 
        SHALL return a RenderedText with non-empty content.
        """
        assume(len(content.strip()) >= 5)
        
        style = TextStyle(
            font_size=font_size,
            bold=bold,
            italic=italic,
        )
        
        renderer = MultimodalOutputRenderer()
        result = renderer.render_text(content, style)
        
        # Property: content SHALL be non-empty
        assert len(result.content) > 0, (
            "RenderedText.content SHALL be non-empty regardless of style"
        )
        
        # Property: style_applied SHALL match input style
        assert result.style_applied.font_size == font_size, (
            "style_applied.font_size SHALL match input"
        )
        assert result.style_applied.bold == bold, (
            "style_applied.bold SHALL match input"
        )
        assert result.style_applied.italic == italic, (
            "style_applied.italic SHALL match input"
        )

    @given(content=non_empty_text_strategy)
    @settings(max_examples=100, deadline=None, suppress_health_check=[HealthCheck.too_slow])
    def test_render_text_generates_html_output(
        self,
        content: str,
    ):
        """
        Feature: autism-science-tutor, Property 9: Text Output Presence
        Validates: Requirements 4.1
        
        For any text content, render_text SHALL generate an HTML 
        representation.
        """
        assume(len(content.strip()) >= 5)
        
        renderer = MultimodalOutputRenderer()
        result = renderer.render_text(content)
        
        # Property: html SHALL be present
        assert result.html is not None, (
            "RenderedText.html SHALL not be None"
        )
        assert isinstance(result.html, str), (
            "RenderedText.html SHALL be a string"
        )
        assert len(result.html) > 0, (
            "RenderedText.html SHALL be non-empty"
        )
        
        # Property: html SHALL contain the content
        assert content in result.html, (
            "RenderedText.html SHALL contain the original content"
        )

    @given(content=non_empty_text_strategy)
    @settings(max_examples=100, deadline=None, suppress_health_check=[HealthCheck.too_slow])
    def test_render_text_generates_markdown_output(
        self,
        content: str,
    ):
        """
        Feature: autism-science-tutor, Property 9: Text Output Presence
        Validates: Requirements 4.1
        
        For any text content, render_text SHALL generate a Markdown 
        representation.
        """
        assume(len(content.strip()) >= 5)
        
        renderer = MultimodalOutputRenderer()
        result = renderer.render_text(content)
        
        # Property: markdown SHALL be present
        assert result.markdown is not None, (
            "RenderedText.markdown SHALL not be None"
        )
        assert isinstance(result.markdown, str), (
            "RenderedText.markdown SHALL be a string"
        )
        assert len(result.markdown) > 0, (
            "RenderedText.markdown SHALL be non-empty"
        )

    @given(
        content=non_empty_text_strategy,
        include_audio=st.booleans(),
        include_comprehension_buttons=st.booleans(),
    )
    @settings(max_examples=100, deadline=None, suppress_health_check=[HealthCheck.too_slow])
    def test_complete_response_always_has_text_message(
        self,
        content: str,
        include_audio: bool,
        include_comprehension_buttons: bool,
    ):
        """
        Feature: autism-science-tutor, Property 9: Text Output Presence
        Validates: Requirements 4.1
        
        For any complete response rendering, the result SHALL always 
        contain a non-empty message text field.
        """
        assume(len(content.strip()) >= 5)
        
        renderer = MultimodalOutputRenderer()
        result = renderer.render_complete_response(
            text_content=content,
            include_audio=include_audio,
            include_comprehension_buttons=include_comprehension_buttons,
        )
        
        # Property: message SHALL be present
        assert "message" in result, (
            "Complete response SHALL contain 'message' key"
        )
        assert result["message"] is not None, (
            "message SHALL not be None"
        )
        assert isinstance(result["message"], str), (
            "message SHALL be a string"
        )
        assert len(result["message"]) > 0, (
            "message SHALL be non-empty"
        )
        
        # Property: text SHALL be present
        assert "text" in result, (
            "Complete response SHALL contain 'text' key"
        )
        assert isinstance(result["text"], RenderedText), (
            "text SHALL be a RenderedText instance"
        )
        assert len(result["text"].content) > 0, (
            "text.content SHALL be non-empty"
        )

    @given(content=explanation_text_strategy)
    @settings(max_examples=100, deadline=None, suppress_health_check=[HealthCheck.too_slow])
    def test_word_count_matches_actual_words(
        self,
        content: str,
    ):
        """
        Feature: autism-science-tutor, Property 9: Text Output Presence
        Validates: Requirements 4.1
        
        For any text content, the word_count SHALL match the actual 
        number of words in the content.
        """
        renderer = MultimodalOutputRenderer()
        result = renderer.render_text(content)
        
        # Calculate expected word count
        expected_word_count = len(content.split())
        
        # Property: word_count SHALL match actual words
        assert result.word_count == expected_word_count, (
            f"word_count ({result.word_count}) SHALL match actual words ({expected_word_count})"
        )

    @given(
        content=non_empty_text_strategy,
        simplify=st.booleans(),
    )
    @settings(max_examples=100, deadline=None, suppress_health_check=[HealthCheck.too_slow])
    def test_simplify_language_still_produces_output(
        self,
        content: str,
        simplify: bool,
    ):
        """
        Feature: autism-science-tutor, Property 9: Text Output Presence
        Validates: Requirements 4.1
        
        For any text content with simplify_language enabled, render_text 
        SHALL still produce non-empty output.
        """
        assume(len(content.strip()) >= 5)
        
        style = TextStyle(simplify_language=simplify)
        
        renderer = MultimodalOutputRenderer()
        result = renderer.render_text(content, style)
        
        # Property: content SHALL be non-empty even with simplification
        assert len(result.content) > 0, (
            "RenderedText.content SHALL be non-empty even with simplify_language"
        )

    def test_empty_content_returns_empty_rendered_text(self):
        """
        Feature: autism-science-tutor, Property 9: Text Output Presence
        Validates: Requirements 4.1
        
        For empty content, render_text SHALL return a RenderedText 
        with empty content (graceful handling).
        """
        renderer = MultimodalOutputRenderer()
        result = renderer.render_text("")
        
        # Property: SHALL return a RenderedText
        assert isinstance(result, RenderedText), (
            "render_text SHALL return a RenderedText for empty input"
        )
        
        # Property: content SHALL be empty string
        assert result.content == "", (
            "RenderedText.content SHALL be empty string for empty input"
        )
        
        # Property: word_count SHALL be 0
        assert result.word_count == 0, (
            "word_count SHALL be 0 for empty input"
        )
        
        # Property: reading_time_seconds SHALL be 0
        assert result.reading_time_seconds == 0, (
            "reading_time_seconds SHALL be 0 for empty input"
        )

    @given(
        content=non_empty_text_strategy,
        highlight=st.booleans(),
        color=st.sampled_from([None, "#000000", "#ff0000", "#0000ff"]),
    )
    @settings(max_examples=100, deadline=None, suppress_health_check=[HealthCheck.too_slow])
    def test_html_includes_style_attributes(
        self,
        content: str,
        highlight: bool,
        color: str,
    ):
        """
        Feature: autism-science-tutor, Property 9: Text Output Presence
        Validates: Requirements 4.1
        
        For any text with style options, the HTML output SHALL include 
        appropriate style attributes.
        """
        assume(len(content.strip()) >= 5)
        
        style = TextStyle(highlight=highlight, color=color)
        
        renderer = MultimodalOutputRenderer()
        result = renderer.render_text(content, style)
        
        # Property: html SHALL contain style attribute
        assert "style=" in result.html, (
            "HTML output SHALL contain style attribute"
        )
        
        # Property: html SHALL contain the content
        assert content in result.html, (
            "HTML output SHALL contain the original content"
        )
        
        # Property: if color is set, it SHALL appear in style
        if color:
            assert color in result.html, (
                f"HTML output SHALL contain color {color} when specified"
            )

    @given(
        content=non_empty_text_strategy,
        bold=st.just(True),
    )
    @settings(max_examples=100, deadline=None, suppress_health_check=[HealthCheck.too_slow])
    def test_bold_style_applied_to_html(
        self,
        content: str,
        bold: bool,
    ):
        """
        Feature: autism-science-tutor, Property 9: Text Output Presence
        Validates: Requirements 4.1
        
        For any text with bold style, the HTML output SHALL include 
        strong tags.
        """
        assume(len(content.strip()) >= 5)
        
        style = TextStyle(bold=bold)
        
        renderer = MultimodalOutputRenderer()
        result = renderer.render_text(content, style)
        
        # Property: html SHALL contain strong tags for bold
        assert "<strong>" in result.html, (
            "HTML output SHALL contain <strong> tag for bold text"
        )
        assert "</strong>" in result.html, (
            "HTML output SHALL contain </strong> closing tag"
        )

    @given(
        content=non_empty_text_strategy,
        italic=st.just(True),
    )
    @settings(max_examples=100, deadline=None, suppress_health_check=[HealthCheck.too_slow])
    def test_italic_style_applied_to_html(
        self,
        content: str,
        italic: bool,
    ):
        """
        Feature: autism-science-tutor, Property 9: Text Output Presence
        Validates: Requirements 4.1
        
        For any text with italic style, the HTML output SHALL include 
        em tags.
        """
        assume(len(content.strip()) >= 5)
        
        style = TextStyle(italic=italic)
        
        renderer = MultimodalOutputRenderer()
        result = renderer.render_text(content, style)
        
        # Property: html SHALL contain em tags for italic
        assert "<em>" in result.html, (
            "HTML output SHALL contain <em> tag for italic text"
        )
        assert "</em>" in result.html, (
            "HTML output SHALL contain </em> closing tag"
        )

    @given(
        content=non_empty_text_strategy,
        bold=st.just(True),
    )
    @settings(max_examples=100, deadline=None, suppress_health_check=[HealthCheck.too_slow])
    def test_bold_style_applied_to_markdown(
        self,
        content: str,
        bold: bool,
    ):
        """
        Feature: autism-science-tutor, Property 9: Text Output Presence
        Validates: Requirements 4.1
        
        For any text with bold style, the Markdown output SHALL include 
        bold markers.
        """
        assume(len(content.strip()) >= 5)
        
        style = TextStyle(bold=bold)
        
        renderer = MultimodalOutputRenderer()
        result = renderer.render_text(content, style)
        
        # Property: markdown SHALL contain ** markers for bold
        assert result.markdown.startswith("**"), (
            "Markdown output SHALL start with ** for bold text"
        )
        assert result.markdown.endswith("**"), (
            "Markdown output SHALL end with ** for bold text"
        )

    @given(
        content=non_empty_text_strategy,
        italic=st.just(True),
    )
    @settings(max_examples=100, deadline=None, suppress_health_check=[HealthCheck.too_slow])
    def test_italic_style_applied_to_markdown(
        self,
        content: str,
        italic: bool,
    ):
        """
        Feature: autism-science-tutor, Property 9: Text Output Presence
        Validates: Requirements 4.1
        
        For any text with italic style, the Markdown output SHALL include 
        italic markers.
        """
        assume(len(content.strip()) >= 5)
        
        style = TextStyle(italic=italic)
        
        renderer = MultimodalOutputRenderer()
        result = renderer.render_text(content, style)
        
        # Property: markdown SHALL contain * markers for italic
        assert result.markdown.startswith("*"), (
            "Markdown output SHALL start with * for italic text"
        )
        assert result.markdown.endswith("*"), (
            "Markdown output SHALL end with * for italic text"
        )
